---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: oabotrefresh
  labels:
    name: oabot.oabotrefresh
    # The toolforge=tool label will cause $HOME and other paths to be mounted from Toolforge
    toolforge: tool
spec:
  # Every Saturday a bit after midnight should be fine
  schedule: "17 2 * * 6"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            toolforge: tool
            spec:
          containers:
          - name: oabotrefresh
            workingDir: /data/project/oabot/www/python/
            image: docker-registry.tools.wmflabs.org/toolforge-python2-sssd-base:latest
            resources:
            # See T273601#6802229
            # Prefilling is usually CPU-bound with 5-10 threads. If there are crashes
            # for insufficient memory, reduce threads in bot.py and maybe ask more resources.
              requests:
                memory: "8Gi"
                cpu: "2"
              limits:
                memory: "8Gi"
                cpu: "2"
            args:
            - /bin/sh
            - -c
            - /data/project/oabot/www/python/oabot_refresh.sh
            env:
            - name: HOME
              value: /data/project/oabot
          completions: 1
          parallelism: 1
          backoffLimit: 1
          restartPolicy: Never
